var darkmode_btn = document.getElementById("darkmode");

changeMode(readCookie());

// generated by chatgpt
const products = [
    {
      id: "1",
      name: "Mouse",
      price: 19.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Mouse.",
      category: "Electronics",
      image_url: "./images/mouse.png"
    },
    {
      id: "2",
      name: "Keyboard",
      price: 29.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Keyboard.",
      category: "Electronics",
      image_url: "./images/keyboard.png"
    },
    {
      id: "3",
      name: "Monitor",
      price: 399.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Monitor.",
      category: "Electronics",
      image_url: "./images/monitor.png"
    },
    {
      id: "4",
      name: "Shirt",
      price: 29.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Shirt.",
      category: "Clothing",
      image_url: "./images/tshirt.png"
    },
    {
      id: "5",
      name: "Jeans",
      price: 49.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Jeans.",
      category: "Clothing",
      image_url: "./images/jeans.png"
    },
    {
      id: "6",
      name: "Shoes",
      price: 79.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Shoes.",
      category: "Clothing",
      image_url: "./images/shoes.jpg"
    },
    {
      id: "7",
      name: "Book",
      price: 9.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Book.",
      category: "Books",
      image_url: "./images/book.jpg"
    },
    {
      id: "8",
      name: "Headphones",
      price: 49.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Headphones.",
      category: "Electronics",
      image_url: "./images/headphones.jpg"
    },
    {
      id: "9",
      name: "Phone",
      price: 599.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Phone.",
      category: "Electronics",
      image_url: "./images/phone.png"
    },
    {
      id: "10",
      name: "Tablet",
      price: 299.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Tablet.",
      category: "Electronics",
      image_url: "./images/tablet.png"
    },
    {
      id: "11",
      name: "Dress",
      price: 39.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Dress.",
      category: "Clothing",
      image_url: "./images/dress.png"
    },
    {
      id: "12",
      name: "Watch",
      price: 199.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Watch.",
      category: "Accessories",
      image_url: "./images/watch.png"
    },
    {
      id: "13",
      name: "Laptop",
      price: 999.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Laptop.",
      category: "Electronics",
      image_url: "./images/laptop.png"
    },
    {
      id: "14",
      name: "Camera",
      price: 499.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Camera.",
      category: "Electronics",
      image_url: "./images/camera.png"
    },
    {
      id: "15",
      name: "Sweater",
      price: 59.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Sweater.",
      category: "Clothing",
      image_url: "./images/sweater.png"
    },
    {
      id: "16",
      name: "Smartwatch",
      price: 249.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Smartwatch.",
      category: "Accessories",
      image_url: "./images/smartwatch.png"
    },
    {
      id: "17",
      name: "Printer",
      price: 199.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Printer.",
      category: "Electronics",
      image_url: "./images/printer.png"
    },
    {
      id: "18",
      name: "Backpack",
      price: 79.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Backpack.",
      category: "Accessories",
      image_url: "./images/backpack.png"
    },
    {
      id: "19",
      name: "Speaker",
      price: 79.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Speaker.",
      category: "Electronics",
      image_url: "./images/speaker.png"
    },
    {
      id: "20",
      name: "Desk",
      price: 199.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit for Desk.",
      category: "Furniture",
      image_url: "./images/desk.png"
    }
];

let product_grids = document.querySelectorAll(".product-grid");
if(product_grids.length !== 0) {
	product_grids.forEach(e => listProducts(products, e));
}
function listProducts(products, element) {
	element.innerHTML = "";
	for(let i = 0; i < products.length; i++) {
		var card = document.createElement("div");
		card.classList.add("card", "card-style");
		card.onclick = ()=> {
			console.log("clicked")
			window.location.href = "./pages/product.html?product_id="+products[i].id;
		}
			var img = document.createElement("img");
			img.classList.add("card-img-top");
			img.src = products[i].image_url;
			card.appendChild(img);

			var card_body = document.createElement("div");
			card_body.classList.add("card-body");
				var name = document.createElement("h5");
				name.classList.add("card-title");
				name.innerText = products[i].name;
				card_body.appendChild(name);

				var price = document.createElement("p");
				price.classList.add("card-text");
				price.innerText = products[i].price + "₺";
				card_body.appendChild(price);
			card.appendChild(card_body);
		element.appendChild(card);
	}
}

function readCookie() {
    return document.cookie.split(";")[0].split("=")[1];
}
function changeCookie(mode) {
    var date = new Date();
    date.setDate(date.getDate()+30);
    document.cookie = "theme="+mode+"; expires="+date.toUTCString()+"; path=/";
}
function changeMode(mode) {
    changeCookie(mode);
    document.getElementsByTagName("html")[0].setAttribute("data-bs-theme", mode);
    darkmode_btn.classList.remove("btn-"+mode);
    darkmode_btn.classList.add(mode === "dark" ? "btn-light" : "btn-dark");
    darkmode_btn.innerText = mode === "dark" ? "☀️" : "🌙";
}

darkmode_btn.addEventListener('click',()=>changeMode(darkmode_btn.innerText === "🌙" ? "dark" : "light"))